#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6633)

    info( '*** Add switches\n')
    s7 = net.addSwitch('s7', cls=OVSKernelSwitch)
    s12 = net.addSwitch('s12', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)
    s14 = net.addSwitch('s14', cls=OVSKernelSwitch)
    s16 = net.addSwitch('s16', cls=OVSKernelSwitch)
    s20 = net.addSwitch('s20', cls=OVSKernelSwitch)
    s10 = net.addSwitch('s10', cls=OVSKernelSwitch)
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s15 = net.addSwitch('s15', cls=OVSKernelSwitch)
    s18 = net.addSwitch('s18', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)
    s5 = net.addSwitch('s5', cls=OVSKernelSwitch)
    s11 = net.addSwitch('s11', cls=OVSKernelSwitch)
    s9 = net.addSwitch('s9', cls=OVSKernelSwitch)
    s8 = net.addSwitch('s8', cls=OVSKernelSwitch)
    s13 = net.addSwitch('s13', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s19 = net.addSwitch('s19', cls=OVSKernelSwitch)
    s17 = net.addSwitch('s17', cls=OVSKernelSwitch)
    s6 = net.addSwitch('s6', cls=OVSKernelSwitch)

    info( '*** Add hosts\n')
    h35 = net.addHost('h35', cls=Host, ip='10.0.0.35', defaultRoute=None)
    h31 = net.addHost('h31', cls=Host, ip='10.0.0.31', defaultRoute=None)
    h17 = net.addHost('h17', cls=Host, ip='10.0.0.17', defaultRoute=None)
    h26 = net.addHost('h26', cls=Host, ip='10.0.0.26', defaultRoute=None)
    h16 = net.addHost('h16', cls=Host, ip='10.0.0.16', defaultRoute=None)
    h3 = net.addHost('h3', cls=Host, ip='10.0.0.3', defaultRoute=None)
    h43 = net.addHost('h43', cls=Host, ip='10.0.0.43', defaultRoute=None)
    h38 = net.addHost('h38', cls=Host, ip='10.0.0.38', defaultRoute=None)
    h19 = net.addHost('h19', cls=Host, ip='10.0.0.19', defaultRoute=None)
    h18 = net.addHost('h18', cls=Host, ip='10.0.0.18', defaultRoute=None)
    h4 = net.addHost('h4', cls=Host, ip='10.0.0.4', defaultRoute=None)
    h15 = net.addHost('h15', cls=Host, ip='10.0.0.15', defaultRoute=None)
    h12 = net.addHost('h12', cls=Host, ip='10.0.0.12', defaultRoute=None)
    h44 = net.addHost('h44', cls=Host, ip='10.0.0.44', defaultRoute=None)
    h1 = net.addHost('h1', cls=Host, ip='10.0.0.1', defaultRoute=None)
    h9 = net.addHost('h9', cls=Host, ip='10.0.0.9', defaultRoute=None)
    h39 = net.addHost('h39', cls=Host, ip='10.0.0.39', defaultRoute=None)
    h20 = net.addHost('h20', cls=Host, ip='10.0.0.20', defaultRoute=None)
    h34 = net.addHost('h34', cls=Host, ip='10.0.0.34', defaultRoute=None)
    h27 = net.addHost('h27', cls=Host, ip='10.0.0.27', defaultRoute=None)
    h5 = net.addHost('h5', cls=Host, ip='10.0.0.5', defaultRoute=None)
    h14 = net.addHost('h14', cls=Host, ip='10.0.0.14', defaultRoute=None)
    h42 = net.addHost('h42', cls=Host, ip='10.0.0.42', defaultRoute=None)
    h30 = net.addHost('h30', cls=Host, ip='10.0.0.30', defaultRoute=None)
    h37 = net.addHost('h37', cls=Host, ip='10.0.0.37', defaultRoute=None)
    h21 = net.addHost('h21', cls=Host, ip='10.0.0.21', defaultRoute=None)
    h7 = net.addHost('h7', cls=Host, ip='10.0.0.7', defaultRoute=None)
    h8 = net.addHost('h8', cls=Host, ip='10.0.0.8', defaultRoute=None)
    h40 = net.addHost('h40', cls=Host, ip='10.0.0.40', defaultRoute=None)
    h22 = net.addHost('h22', cls=Host, ip='10.0.0.22', defaultRoute=None)
    h6 = net.addHost('h6', cls=Host, ip='10.0.0.6', defaultRoute=None)
    h32 = net.addHost('h32', cls=Host, ip='10.0.0.32', defaultRoute=None)
    h36 = net.addHost('h36', cls=Host, ip='10.0.0.36', defaultRoute=None)
    h28 = net.addHost('h28', cls=Host, ip='10.0.0.28', defaultRoute=None)
    h23 = net.addHost('h23', cls=Host, ip='10.0.0.23', defaultRoute=None)
    h11 = net.addHost('h11', cls=Host, ip='10.0.0.11', defaultRoute=None)
    h2 = net.addHost('h2', cls=Host, ip='10.0.0.2', defaultRoute=None)
    h13 = net.addHost('h13', cls=Host, ip='10.0.0.13', defaultRoute=None)
    h10 = net.addHost('h10', cls=Host, ip='10.0.0.10', defaultRoute=None)
    h33 = net.addHost('h33', cls=Host, ip='10.0.0.33', defaultRoute=None)
    h24 = net.addHost('h24', cls=Host, ip='10.0.0.24', defaultRoute=None)
    h25 = net.addHost('h25', cls=Host, ip='10.0.0.25', defaultRoute=None)
    h41 = net.addHost('h41', cls=Host, ip='10.0.0.41', defaultRoute=None)
    h29 = net.addHost('h29', cls=Host, ip='10.0.0.29', defaultRoute=None)
    h45 = net.addHost('h45', cls=Host, ip='10.0.0.45', defaultRoute=None)

    info( '*** Add links\n')
    net.addLink(s1, s17)
    net.addLink(s2, s17)
    net.addLink(s3, s17)
    net.addLink(s4, s17)
    net.addLink(s5, s18)
    net.addLink(s6, s18)
    net.addLink(s7, s18)
    net.addLink(s8, s18)
    net.addLink(s19, s9)
    net.addLink(s19, s10)
    net.addLink(s11, s19)
    net.addLink(s12, s19)
    net.addLink(s16, s20)
    net.addLink(s15, s20)
    net.addLink(s14, s20)
    net.addLink(s13, s20)
    net.addLink(s17, s18)
    net.addLink(s17, s20)
    net.addLink(s20, s19)
    net.addLink(s18, s19)
    net.addLink(s17, s19)
    net.addLink(s20, s18)
    net.addLink(h2, s2)
    net.addLink(h3, s3)
    net.addLink(h4, s4)
    net.addLink(h5, s5)
    net.addLink(h6, s6)
    net.addLink(h7, s7)
    net.addLink(h8, s8)
    net.addLink(h9, s9)
    net.addLink(h10, s10)
    net.addLink(h11, s11)
    net.addLink(h12, s12)
    net.addLink(h13, s13)
    net.addLink(h14, s14)
    net.addLink(h15, s15)
    net.addLink(h16, s16)
    net.addLink(h1, s1)
    net.addLink(h18, s1)
    net.addLink(h20, s1)
    net.addLink(h17, s1)
    net.addLink(s2, h19)
    net.addLink(s3, h21)
    net.addLink(s3, h23)
    net.addLink(s4, h22)
    net.addLink(s4, h24)
    net.addLink(s5, h25)
    net.addLink(s5, h27)
    net.addLink(s6, h26)
    net.addLink(s6, h33)
    net.addLink(s6, h36)
    net.addLink(s6, h37)
    net.addLink(s7, h28)
    net.addLink(s7, h29)
    net.addLink(s7, h30)
    net.addLink(s8, h31)
    net.addLink(s8, h34)
    net.addLink(s8, h39)
    net.addLink(h32, s9)
    net.addLink(s10, h35)
    net.addLink(s11, h38)
    net.addLink(s12, h40)
    net.addLink(s13, h41)
    net.addLink(s13, h42)
    net.addLink(s14, h43)
    net.addLink(s15, h44)
    net.addLink(s16, h45)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    net.get('s7').start([c0])
    net.get('s12').start([c0])
    net.get('s4').start([c0])
    net.get('s14').start([c0])
    net.get('s16').start([c0])
    net.get('s20').start([c0])
    net.get('s10').start([c0])
    net.get('s1').start([c0])
    net.get('s15').start([c0])
    net.get('s18').start([c0])
    net.get('s3').start([c0])
    net.get('s5').start([c0])
    net.get('s11').start([c0])
    net.get('s9').start([c0])
    net.get('s8').start([c0])
    net.get('s13').start([c0])
    net.get('s2').start([c0])
    net.get('s19').start([c0])
    net.get('s17').start([c0])
    net.get('s6').start([c0])

    info( '*** Post configure switches and hosts\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

