#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=RemoteController,
                      ip='127.0.0.1',
                      protocol='tcp',
                      port=6633)

    info( '*** Add switches\n')
    s17 = net.addSwitch('s17', cls=OVSKernelSwitch)
    s15 = net.addSwitch('s15', cls=OVSKernelSwitch)
    s20 = net.addSwitch('s20', cls=OVSKernelSwitch)
    s19 = net.addSwitch('s19', cls=OVSKernelSwitch)
    s16 = net.addSwitch('s16', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)
    s7 = net.addSwitch('s7', cls=OVSKernelSwitch)
    s6 = net.addSwitch('s6', cls=OVSKernelSwitch)
    s11 = net.addSwitch('s11', cls=OVSKernelSwitch)
    s9 = net.addSwitch('s9', cls=OVSKernelSwitch)
    s8 = net.addSwitch('s8', cls=OVSKernelSwitch)
    s12 = net.addSwitch('s12', cls=OVSKernelSwitch)
    s13 = net.addSwitch('s13', cls=OVSKernelSwitch)
    s18 = net.addSwitch('s18', cls=OVSKernelSwitch)
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s14 = net.addSwitch('s14', cls=OVSKernelSwitch)
    s5 = net.addSwitch('s5', cls=OVSKernelSwitch)
    s10 = net.addSwitch('s10', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)

    info( '*** Add hosts\n')
    pmu9 = net.addHost('pmu9', cls=Host, ip='10.0.0.25', defaultRoute=None)
    pmu12 = net.addHost('pmu12', cls=Host, ip='10.0.0.28', defaultRoute=None)
    pdc3 = net.addHost('pdc3', cls=Host, ip='10.0.0.3', defaultRoute=None)
    pdc11 = net.addHost('pdc11', cls=Host, ip='10.0.0.11', defaultRoute=None)
    pdc12 = net.addHost('pdc12', cls=Host, ip='10.0.0.12', defaultRoute=None)
    pmu27 = net.addHost('pmu27', cls=Host, ip='10.0.0.43', defaultRoute=None)
    pdc8 = net.addHost('pdc8', cls=Host, ip='10.0.0.8', defaultRoute=None)
    pmu14 = net.addHost('pmu14', cls=Host, ip='10.0.0.30', defaultRoute=None)
    pmu19 = net.addHost('pmu19', cls=Host, ip='10.0.0.35', defaultRoute=None)
    pdc15 = net.addHost('pdc15', cls=Host, ip='10.0.0.15', defaultRoute=None)
    pdc4 = net.addHost('pdc4', cls=Host, ip='10.0.0.4', defaultRoute=None)
    pmu22 = net.addHost('pmu22', cls=Host, ip='10.0.0.38', defaultRoute=None)
    pdc5 = net.addHost('pdc5', cls=Host, ip='10.0.0.5', defaultRoute=None)
    pmu5 = net.addHost('pmu5', cls=Host, ip='10.0.0.21', defaultRoute=None)
    pmu10 = net.addHost('pmu10', cls=Host, ip='10.0.0.26', defaultRoute=None)
    pmu4 = net.addHost('pmu4', cls=Host, ip='10.0.0.20', defaultRoute=None)
    pmu25 = net.addHost('pmu25', cls=Host, ip='10.0.0.41', defaultRoute=None)
    pmu13 = net.addHost('pmu13', cls=Host, ip='10.0.0.29', defaultRoute=None)
    pdc9 = net.addHost('pdc9', cls=Host, ip='10.0.0.9', defaultRoute=None)
    pmu17 = net.addHost('pmu17', cls=Host, ip='10.0.0.33', defaultRoute=None)
    pmu28 = net.addHost('pmu28', cls=Host, ip='10.0.0.44', defaultRoute=None)
    pmu6 = net.addHost('pmu6', cls=Host, ip='10.0.0.22', defaultRoute=None)
    pdc6 = net.addHost('pdc6', cls=Host, ip='10.0.0.6', defaultRoute=None)
    pmu1 = net.addHost('pmu1', cls=Host, ip='10.0.0.17', defaultRoute=None)
    pmu8 = net.addHost('pmu8', cls=Host, ip='10.0.0.24', defaultRoute=None)
    pmu29 = net.addHost('pmu29', cls=Host, ip='10.0.0.45', defaultRoute=None)
    pmu15 = net.addHost('pmu15', cls=Host, ip='10.0.0.31', defaultRoute=None)
    pmu16 = net.addHost('pmu16', cls=Host, ip='10.0.0.32', defaultRoute=None)
    pdc7 = net.addHost('pdc7', cls=Host, ip='10.0.0.7', defaultRoute=None)
    pmu26 = net.addHost('pmu26', cls=Host, ip='10.0.0.42', defaultRoute=None)
    pmu30 = net.addHost('pmu30', cls=Host, ip='10.0.0.46', defaultRoute=None)
    pdc2 = net.addHost('pdc2', cls=Host, ip='10.0.0.2', defaultRoute=None)
    pdc1 = net.addHost('pdc1', cls=Host, ip='10.0.0.1', defaultRoute=None)
    pmu23 = net.addHost('pmu23', cls=Host, ip='10.0.0.39', defaultRoute=None)
    pdc14 = net.addHost('pdc14', cls=Host, ip='10.0.0.14', defaultRoute=None)
    pmu21 = net.addHost('pmu21', cls=Host, ip='10.0.0.37', defaultRoute=None)
    pmu11 = net.addHost('pmu11', cls=Host, ip='10.0.0.27', defaultRoute=None)
    pdc16 = net.addHost('pdc16', cls=Host, ip='10.0.0.16', defaultRoute=None)
    pdc10 = net.addHost('pdc10', cls=Host, ip='10.0.0.10', defaultRoute=None)
    pmu7 = net.addHost('pmu7', cls=Host, ip='10.0.0.23', defaultRoute=None)
    pdc13 = net.addHost('pdc13', cls=Host, ip='10.0.0.13', defaultRoute=None)
    pmu20 = net.addHost('pmu20', cls=Host, ip='10.0.0.36', defaultRoute=None)
    pmu3 = net.addHost('pmu3', cls=Host, ip='10.0.0.19', defaultRoute=None)
    pmu24 = net.addHost('pmu24', cls=Host, ip='10.0.0.40', defaultRoute=None)
    pmu2 = net.addHost('pmu2', cls=Host, ip='10.0.0.18', defaultRoute=None)
    pmu18 = net.addHost('pmu18', cls=Host, ip='10.0.0.34', defaultRoute=None)

    info( '*** Add links\n')
    net.addLink(s1, s17)
    net.addLink(s2, s17)
    net.addLink(s3, s17)
    net.addLink(s4, s17)
    net.addLink(s5, s18)
    net.addLink(s6, s18)
    net.addLink(s7, s18)
    net.addLink(s8, s18)
    net.addLink(s19, s9)
    net.addLink(s19, s10)
    net.addLink(s11, s19)
    net.addLink(s12, s19)
    net.addLink(s16, s20)
    net.addLink(s15, s20)
    net.addLink(s14, s20)
    net.addLink(s13, s20)
    net.addLink(s17, s18)
    net.addLink(s17, s20)
    net.addLink(s20, s19)
    net.addLink(s18, s19)
    net.addLink(s17, s19)
    net.addLink(s20, s18)
    net.addLink(pdc2, s2)
    net.addLink(pdc3, s3)
    net.addLink(pdc4, s4)
    net.addLink(pdc5, s5)
    net.addLink(pdc6, s6)
    net.addLink(pdc7, s7)
    net.addLink(pdc8, s8)
    net.addLink(pdc9, s9)
    net.addLink(pdc10, s10)
    net.addLink(pdc11, s11)
    net.addLink(pdc12, s12)
    net.addLink(pdc13, s13)
    net.addLink(pdc14, s14)
    net.addLink(pdc15, s15)
    net.addLink(pdc16, s16)
    net.addLink(pdc1, s1)
    net.addLink(pmu2, s1)
    net.addLink(pmu4, s1)
    net.addLink(pmu1, s1)
    net.addLink(s2, pmu3)
    net.addLink(s3, pmu5)
    net.addLink(s3, pmu7)
    net.addLink(s4, pmu6)
    net.addLink(s4, pmu8)
    net.addLink(s5, pmu9)
    net.addLink(s5, pmu11)
    net.addLink(s6, pmu10)
    net.addLink(s6, pmu17)
    net.addLink(s6, pmu20)
    net.addLink(s6, pmu21)
    net.addLink(s7, pmu12)
    net.addLink(s7, pmu13)
    net.addLink(s7, pmu14)
    net.addLink(s8, pmu15)
    net.addLink(s8, pmu18)
    net.addLink(s8, pmu23)
    net.addLink(pmu16, s9)
    net.addLink(s10, pmu19)
    net.addLink(s11, pmu22)
    net.addLink(s12, pmu24)
    net.addLink(s13, pmu25)
    net.addLink(s13, pmu26)
    net.addLink(s14, pmu27)
    net.addLink(s15, pmu28)
    net.addLink(s16, pmu29)
    net.addLink(pmu30, s14)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    net.get('s17').start([c0])
    net.get('s15').start([c0])
    net.get('s20').start([c0])
    net.get('s19').start([c0])
    net.get('s16').start([c0])
    net.get('s3').start([c0])
    net.get('s4').start([c0])
    net.get('s7').start([c0])
    net.get('s6').start([c0])
    net.get('s11').start([c0])
    net.get('s9').start([c0])
    net.get('s8').start([c0])
    net.get('s12').start([c0])
    net.get('s13').start([c0])
    net.get('s18').start([c0])
    net.get('s1').start([c0])
    net.get('s14').start([c0])
    net.get('s5').start([c0])
    net.get('s10').start([c0])
    net.get('s2').start([c0])

    info( '*** Post configure switches and hosts\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

